wallpaper {
    monitor = desc:Xiaomi Corporation Mi Monitor 7041110012098
    path = /home/shingetsu/Pictures/wallpapers/b-340.jpg
    fit_mode = cover
}

wallpaper {
    monitor = desc:Samsung Electric Company C32JG5x HTOKA00331
    path = /home/shingetsu/Pictures/wallpapers/b-340.jpg
    fit_mode = cover
}

splash = false
ipc = true
