$mainMod = SUPER

bind = $mainMod, TAB, hyprexpo:expo, toggle	#win+tab like in windows

submap = hyprexpo
    bind = , left, hyprexpo:kb_focus, left
    bind = , right, hyprexpo:kb_focus, right
    bind = , up,    hyprexpo:kb_focus, up
    bind = , down,  hyprexpo:kb_focus, down
    bind = , return, hyprexpo:kb_confirm
submap = reset