wallpaper {
    monitor = desc:Xiaomi Corporation Mi Monitor 7041110012098
    path = /home/shingetsu/Pictures/wallpapers/b-143.jpg
    fit_mode = cover
}

wallpaper {
    monitor = desc:Acer Technologies Acer XF240H 0x7300562E
    path = /home/shingetsu/Pictures/wallpapers/b-143.jpg
    fit_mode = cover
}

splash = false
ipc = true
